name: The Grid Showcase
favicon: null
layout_spectrum: 0
typography_spectrum: 0.91228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#1f1414"
    - "#d12b2f"
    - "#fff7b4"
    - "#6c5b5a"
    - "#b0a38e"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
