name: The Grid Showcase
favicon: null
layout_spectrum: 0.19298
typography_spectrum: 0.91228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#1c1d20"
    - "#ffffff"
    - "#5b5955"
    - "#8e8f91"
    - "#cfc782"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
